source 'http://rubygems.org'

gem "rake"
gem "rails", "4.2.4"
gem "infopark_fiona_connector", "7.0.1.beta2"
gem "infopark_crm_connector"
gem "infopark_ses", :path => ".."
gem "sqlite3"
gem "mysql2"
gem "mysql_blob_streaming"

group :test do
  gem "rspec"
  gem "rspec-rails"
  gem "rspec-mocks"
  gem "prawn" # test indexing of PDFs (made on the fly)
end
